//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymOOP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class clan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clan()
        {
            this.Prisustvoes = new HashSet<Prisustvo>();
            this.Termins = new HashSet<Termin>();
        }
    
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<int> brTelefona { get; set; }
        public string adresa { get; set; }
        public string email { get; set; }
        public string pol { get; set; }
        public string JMBG { get; set; }
        public Nullable<System.DateTime> datumUpisa { get; set; }
        public Nullable<System.DateTime> UplataClanarine { get; set; }
        public string DodelaTrenera { get; set; }
        public string Clanarina { get; set; }
        public string Zauzet { get; set; }
        public string Grupa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prisustvo> Prisustvoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termin> Termins { get; set; }
    }
}
