//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymOOP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        public int IDKorisnika { get; set; }
        public string ImeiPrezime { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string tip { get; set; }
        public string potvrda { get; set; }
    }
}
