//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymOOP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        public int IDTermina { get; set; }
        public string IDClan { get; set; }
        public string Trener { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Vreme { get; set; }
    
        public virtual clan clan { get; set; }
    }
}
